services:
  nginx:
    image: nginx
    container_name: steffbeckers_nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/api.conf:/etc/nginx/api.conf:ro
      - ./nginx/common.conf:/etc/nginx/common.conf:ro
      - ./nginx/common_location.conf:/etc/nginx/common_location.conf:ro
      - ./nginx/html/:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl/steffbeckers.local.crt:/etc/ssl/certs/steffbeckers.local.crt
      - ./nginx/ssl/steffbeckers.local.key:/etc/ssl/private/steffbeckers.local.key
      - ./nginx/ssl/ssl.conf:/etc/nginx/ssl.conf:ro
    networks:
      - steffbeckers
  redis:
    image: redis
    container_name: steffbeckers_redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - steffbeckers
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: steffbeckers_redis-commander
    hostname: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    networks:
      - steffbeckers
  rabbitmq:
    image: rabbitmq:management
    container_name: steffbeckers_rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=steff
      - RABBITMQ_DEFAULT_PASS=Pqdky8ozQBww7tqyi!hM
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - steffbeckers
  mailhog:
    image: mailhog/mailhog
    container_name: steffbeckers_mailhog
    restart: always
    logging:
      driver: "none"
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - steffbeckers

networks:
  steffbeckers:
    name: steffbeckers
